"""
tests/test_sky_assets.py
========================
Schema validation for the static sky-map asset files generated by
scripts/build_sky_assets.py.

Tests are skipped gracefully when the files do not yet exist, so CI passes
before the build script has been run.

Run after generating assets:
    python scripts/build_sky_assets.py
    pytest tests/test_sky_assets.py -v
"""

import json
import pytest
from pathlib import Path

FRONTEND_DATA = Path(__file__).resolve().parent.parent / "frontend" / "data"

STARS_FILE     = FRONTEND_DATA / "stars.json"
CONST_FILE     = FRONTEND_DATA / "constellations.json"
MILKYWAY_FILE  = FRONTEND_DATA / "milkyway.json"


# ─────────────────────────────────────────────────────────────────────────────
#  stars.json
# ─────────────────────────────────────────────────────────────────────────────

@pytest.mark.skipif(not STARS_FILE.exists(), reason="stars.json not yet generated")
def test_stars_is_list():
    data = json.loads(STARS_FILE.read_text())
    assert isinstance(data, list), "stars.json must be a JSON array"


@pytest.mark.skipif(not STARS_FILE.exists(), reason="stars.json not yet generated")
def test_stars_schema():
    data = json.loads(STARS_FILE.read_text())
    assert len(data) > 0, "stars.json must not be empty"
    for i, star in enumerate(data[:50]):  # sample first 50
        assert "ra_h"    in star, f"star[{i}] missing ra_h"
        assert "dec_deg" in star, f"star[{i}] missing dec_deg"
        assert "mag"     in star, f"star[{i}] missing mag"
        assert isinstance(star["ra_h"],    float), f"star[{i}].ra_h must be float"
        assert isinstance(star["dec_deg"], float), f"star[{i}].dec_deg must be float"
        assert isinstance(star["mag"],     float), f"star[{i}].mag must be float"
        assert 0.0 <= star["ra_h"] < 24.0,       f"star[{i}].ra_h out of range"
        assert -90.0 <= star["dec_deg"] <= 90.0,  f"star[{i}].dec_deg out of range"


@pytest.mark.skipif(not STARS_FILE.exists(), reason="stars.json not yet generated")
def test_stars_file_size():
    size_kb = STARS_FILE.stat().st_size / 1024
    assert size_kb < 1024, f"stars.json is {size_kb:.1f} KB — must be < 1 MB"


# ─────────────────────────────────────────────────────────────────────────────
#  constellations.json
# ─────────────────────────────────────────────────────────────────────────────

@pytest.mark.skipif(not CONST_FILE.exists(), reason="constellations.json not yet generated")
def test_constellations_is_list():
    data = json.loads(CONST_FILE.read_text())
    assert isinstance(data, list), "constellations.json must be a JSON array"


@pytest.mark.skipif(not CONST_FILE.exists(), reason="constellations.json not yet generated")
def test_constellations_schema():
    data = json.loads(CONST_FILE.read_text())
    assert len(data) > 0, "constellations.json must not be empty"
    for i, c in enumerate(data):
        assert "name"     in c,               f"constellation[{i}] missing name"
        assert "segments" in c,               f"constellation[{i}] missing segments"
        assert isinstance(c["name"], str),    f"constellation[{i}].name must be str"
        assert isinstance(c["segments"], list), f"constellation[{i}].segments must be list"
        for j, seg in enumerate(c["segments"]):
            assert len(seg) == 4, (
                f"constellation[{i}].segments[{j}] must have 4 elements [ra1,dec1,ra2,dec2]"
            )


@pytest.mark.skipif(not CONST_FILE.exists(), reason="constellations.json not yet generated")
def test_constellations_file_size():
    size_kb = CONST_FILE.stat().st_size / 1024
    assert size_kb < 512, f"constellations.json is {size_kb:.1f} KB — must be < 500 KB"


# ─────────────────────────────────────────────────────────────────────────────
#  milkyway.json
# ─────────────────────────────────────────────────────────────────────────────

@pytest.mark.skipif(not MILKYWAY_FILE.exists(), reason="milkyway.json not yet generated")
def test_milkyway_schema():
    data = json.loads(MILKYWAY_FILE.read_text())
    assert isinstance(data, dict),          "milkyway.json must be a JSON object"
    assert "points"    in data,             "milkyway.json missing 'points'"
    assert "width_deg" in data,             "milkyway.json missing 'width_deg'"
    assert isinstance(data["points"], list), "'points' must be a list"
    assert len(data["points"]) > 10,        "'points' must have more than 10 entries"
    for i, pt in enumerate(data["points"][:10]):
        assert len(pt) == 2, f"milkyway.points[{i}] must be [ra_h, dec_deg]"
